// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ayrjnymlpd","name":"Bloquinho","description":"","endpoint":"https://ayrjnymlpd.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/bloco","/bloco/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:3c6d58f3-e5f0-4f1b-a785-235c9767f272',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'bloquinhossp-hosting-mobilehub-139992012',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3qyrkppassn53.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"bloquinhossp-mobilehub-139992012-Blocos","attributes":[{"name":"blocoId","type":"S"},{"name":"bloco_name","type":"S"},{"name":"description","type":"S"},{"name":"end_time","type":"S"},{"name":"facebook_page","type":"S"},{"name":"is_draft","type":"N"},{"name":"latitude","type":"N"},{"name":"lineup","type":"SS"},{"name":"longitude","type":"N"},{"name":"start_time","type":"S"}],"indexes":[{"indexName":"draft-index","hashKey":"is_draft"}],"region":"us-east-1","hashKey":"blocoId"}],
    'aws_mobile_analytics_app_id': '76c9c7db94ae41f88edd39d53259b360',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5fc8b3c8-097b-4ae0-9f5d-eb423e82160d',
    'aws_project_name': 'BloquinhosSp2018',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'bloquinhossp-deployments-mobilehub-139992012',
    'aws_resource_name_prefix': 'bloquinhossp-mobilehub-139992012',
}

export default awsmobile;
